### ISSUE TITLE
remove the compiled PhyloAcc in your dir

### ISSUE THREAD

**Issue by beyondpie** [xyz111131/PhyloAcc#16]
Hi, Zhirui,
I notice that there is a "compiled" PhyloAcc in your directory. I think it should be deleted?

**Comment by xyz111131** [comment]
Just deleted.

**Comment by beyondpie** [comment]
Thanks, Zhirui.
I am now re trying to update the compile procedure. Hope to send you a PR as soon as possible.
I will now close this issue.
