### ISSUE TITLE
Is it necessary to add the ancestor's sequences?

### ISSUE THREAD

**Issue by Secretloong** [xyz111131/PhyloAcc#21]
I found the ancestors in your example of the input FASTA file. Is it necessary to use the ancestor's sequences in `phyloAcc`?
If the ancestors were included, would they change the results?
If I would like to test only the ancestor's state, parent's branch could be used by `phyloP` with `--branch`. How about phyloAcc to test only the ancestor's branch?
If users have no `Cactus` alignments and its estimated ansectors, would you have any suggestions to estimate the ancestors quickly?

Thanks

**Comment by xyz111131** [comment]
Nope, you don't need the ancestor sequences. PhyloAcc will estimate the ancestor sequences. I think you were looking at a simulation example where it has the ancestor sequences. The assumption of PhyloAcc is that if an ancestor sequence is accelerated, its children will be accelerated too. So in your case, you could specify the target species as the children of the ancestor branch.

**Comment by Secretloong** [comment]
Thanks, that makes sense
