### ISSUE TITLE
Data overflow in loading configurations

### ISSUE THREAD

**Issue by Secretloong** [xyz111131/PhyloAcc#22]
Hi, line 100 in [https://github.com/xyz111131/PhyloAcc/blob/master/SRC/main.cpp](url) you used  `const int BUFF_SIZE = 1024;`

But if the configurations text is longer then 1024 bytes, it would be cause `PhyloAcc` into an infinite loop in configurations loading. Especialy the species lists are very long or the name is very long. When I edited it to `16384`, it works for me. 

Just in case, do you think if this edition would effect `PhyloAcc` results? And, if it is necessary could you fix this limitation?

Best wishes

**Comment by xyz111131** [comment]
Thanks for the comment. I don't think it would affect PhyloAcc's result. I'll increase the BUFF_SIZE.

**Comment by Secretloong** [comment]
Thank you!
